image: gradle:alpine

stages:
  - build
  - test
  - package
  - coverage

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-19.jdk
  - export JAVA_HOME

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

package:
  stage: package
  script: ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/*
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

coverage:
  stage: coverage
  script: ./gradlew jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/index.html