image: gradle:alpine

stages:
  - build
  - test
  - package
  - coverage

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle build


test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

package:
  stage: package
  script: gradle bootJar
  artifacts:
    paths:
      - build/libs/*
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

coverage:
  stage: coverage
  script: gradle jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/index.html